openapi: 3.1.0
info:
  title: AAW-Skills
  description: AAW-Skills
  version: 1.0.0
servers:
  - url: '{scheme}://{host}:{port}/api/v1'
    variables:
      scheme:
        default: "http"
      hostname:
        default: "aaw.ngimenez.fr"
      port:
        default: "8000"
paths:
  # "/auth":
  "/startAuth":
    summary: Start the identification process with discord
    description: Start all of the discord authentification process
    post:
      parameters:
        - name: success_redirect
          in: query
          description: The URL to redirect after auth success
          required: true
          schema:
            type: string
        - name: error_redirect
          in: query
          description: The URL to redirect after auth failed
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the discord auth URL
          content:
            "text/plain":
              description: Discord Auth URL
  "/discordAuth":
    summary: Redirect from discord
    description: The discord auth endpoint
    get:
      parameters:
        - name: code
          in: query
          description: The discord code to generate token
          required: true
          schema:
            type: string
        - name: state
          in: query
          description: A data that is returned
          required: true
          schema:
            type: string
    responses:
      200:
        description: Everything ok
  "/skills":
    summary: List of skills
    description: Get the list of skills
    get:
      summary: Get the list of skills
      responses:
        200:
          description: List of existing skills
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: string

  "/skills/my":
    summary: User's skills
    description: Get or manage authenticated user's skills
    get:
      summary: Get authenticated user's skills
      responses:
        200:
          description: List of skills with associated grade
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user_skill"
    put:
      summary: Set a skill for authenticated user
      requestBody:
        content:
          "application/json":
            schema:
              $ref: '#/components/schemas/user_skill'
      responses:
        200:
          description: Update successful.
        400:
          description: Invalid request body.
        404:
          description: Unknown skill.
    delete:
      summary: Remove a skill for authenticated user
      requestBody:
        content:
          "text/plain":
            description: Name of the skill to remove
      responses:
        200:
          description: Removed skill successfully.
        404:
          description: Unknown skill.

  /users:
    get:
      summary: List users
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: "#/components/parameters/limit"
        - name: skills
          in: query
          description: If true, the response will contain the skills property.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: List of users
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user_info"

  "/users/search/{query}":
    get:
      summary: Find users by name
      parameters:
      - name: query
        in: path
        description: First chars of the user name to look for.
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/offset'
      - $ref: "#/components/parameters/limit"
      responses:
        200:
          description: Results - list of users
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/basic_user_info"

  "/users/me":
    get:
      summary: Get information about authenticated user
      responses:
        200:
          description: Information about authenticated user
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/user_info"
        401:
          description: Not authenticated

  "/users/{discord_id}":
    summary: Get information about a user
    parameters:
      - name: discord_id
        in: path
        schema:
          type: string
        required: true
    get:
      summary: Get information about a user
      responses:
        200:
          description: User information



components:
  parameters:
    offset:
      name: offset
      in: query
      description: Number of skipped results. Used for pagination.
      required: false
      schema:
        type: integer
        default: 0
    limit:
      name: count
      in: query
      description: Maximum number of results. Used for pagination.
      required: false
      schema:
        type: integer
        default: 25
  schemas:
    user_skill:
      type: object
      properties:
        name:
          description: Skill name
          type: string
        grade:
          description: Grade from 1 to 10 (included)
          type: integer
          exclusiveMinimum: 0
          maximum: 10
    basic_user_info:
      type: object
      properties:
        name:
          description: User name
          type: string
        discord_id:
          description: Discord ID (numeric string)
          type: string
        last_update:
          description: Last update date in French (France) format
          type: string
    user_info:
      type: object
      properties:
        name:
          description: User name
          type: string
        discord_id:
          description: Discord ID (numeric string)
          type: string
        last_update:
          description: Last update date in French (France) format
          type: string
        skills:
          description: List of skills
          type: array
          items:
            $ref: "#/components/schemas/user_skill"
